name: 'Python security scanning action'
description: 'Currently on'
inputs:
  bandit-config:
    description: 'Bandit configuration file'
    required: false
  input-dir:
    description: 'Directory to scan'
    required: false
    default: '.'
  format:
    description: 'Output format (txt, csv, json, xml, yaml). Default: json'
    required: false
    default: 'json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.format }}
    - ${{ inputs.bandit-config }}
    - ${{ inputs.input-dir }}