name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build package
        run: |
          set -e
          poetry version ${{ github.event.release.tag_name }}
          poetry build

      - name: Publish package
        run: |
          set -e
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish -n
